version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    environment:
      - GO_ENV=production
    depends_on:
      - blockchain

  blockchain:
    image: hyperledger/fabric-peer:2.4
    container_name: fabric_peer
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    volumes:
      - ./fabric-config:/etc/hyperledger/fabric
    ports:
      - "7051:7051"
